export async function help() {
  return [
    "*Commandes Ayumi* 🤖",
    "",
    "*Général*",
    "• /ping                       — test",
    "• /help                       — cette aide",
    "• /ayumi <question>           — parler à l'IA (Gemini)",
    "• /stats                      — stats du groupe",
    "• /warns [@user]              — voir les warns",
    "",
    "*Sondages*",
    "• /poll Question | opt1 | opt2 | opt3  (alias /sondage)",
    "",
    "*Modération (admins)*",
    "• /del                        — supprime le message cité",
    "• /warn @user raison          — ajouter un warn",
    "• /clearwarns @user           — reset les warns",
    "• /kick @user                 — retirer (alias /ban)",
    "• /promote @user              — passer admin",
    "• /demote @user               — retirer admin",
    "• /tagall [message]           — mentionner tout le monde",
    "",
    "_Le bot doit être admin du groupe pour /del /kick /promote._",
    "_Dashboard: http://localhost:3000_",
  ].join("\n");
}
