export async function help() {
  return [
    "*Commandes Ayumi* 🤖",
    "",
    "*Général*",
    "• /ping · /help · /stats",
    "• /ayumi <question>     — parler à l'IA",
    "",
    "*Mémoire 🧠*",
    "• /remember clé = valeur · /memories · /forget <clé|all>",
    "_Ayumi détecte aussi automatiquement vos infos (anniv, ville, métier…)._",
    "",
    "*Jeux 🎮*",
    "• /jeu                  — liste",
    "• /quiz · /devinette · /vraifaux · /motmystere",
    "• /culture · /quisuisje · /blindtext · /actionverite · /roleplay",
    "• /jouer · /score · /stop · /classement",
    "• /creerjeu <thème>     — Ayumi invente un jeu",
    "",
    "*Sondages*",
    "• /poll Question | opt1 | opt2 | opt3",
    "",
    "*Modération (admins)*",
    "• /del · /warn · /warns · /clearwarns",
    "• /kick · /promote · /demote · /tagall",
    "",
    "_Dashboard : http://localhost:3000_",
  ].join("\n");
}
