export async function help() {
  return [
    "*Commandes Ayumi* 🤖",
    "",
    "*Général*",
    "• /ping                    — test",
    "• /help                    — cette aide",
    "• /ayumi <question>        — parler à l'IA",
    "• /stats                   — stats du groupe",
    "",
    "*Mémoire 🧠*",
    "• /remember clé = valeur   — Ayumi mémorise (alias /retiens)",
    "• /memories                — tes souvenirs (alias /souvenirs)",
    "• /forget <clé>            — oublie (ou /forget all)",
    "",
    "*Jeux 🎮*",
    "• /jeu                     — liste des jeux",
    "• /quiz                    — culture générale",
    "• /devinette               — énigme",
    "• /vraifaux                — vrai ou faux",
    "• /motmystere              — devine le mot",
    "• /stop                    — arrêter la partie",
    "• /classement              — top joueurs (alias /leaderboard)",
    "",
    "*Sondages*",
    "• /poll Question | opt1 | opt2 | opt3",
    "",
    "*Modération (admins)*",
    "• /del                     — supprime le message cité",
    "• /warn @user raison",
    "• /warns [@user] · /clearwarns @user",
    "• /kick @user · /promote @user · /demote @user",
    "• /tagall [message]        — mentionner tout le monde",
    "",
    "_Dashboard : http://localhost:3000_",
  ].join("\n");
}
